default:
    study_name: "C. elegans Tintori 16-cell"
    study_description: "Data from Tintori, S. C., Nishimura, E. O., Golden, P., Lieb, J. D., & Goldstein, B. (2016). A transcriptional lineage of the early C. elegans embryo. Developmental cell, 38(4), 430-444."
    organism: "cel" # choose from mmu (mouse), hsa (human) and cel (C.elegans)
    feature_name_column: "gene_name"
    feature_id_column: "gene_name" # Set this to be same as name col if feature id column not available
